"""Generate deterministic Python scripts for execution inside FreeCAD."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from ...geometry.fretboard import FretboardSurface
from ...geometry.neck import NeckBackSurface
from ...geometry.primitives import Point3D
from .exceptions import FreeCADBackendError

_VALID_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True, slots=True)
class FreeCADScriptExporter:
    """Render loft-ready geometry as a standalone FreeCAD Python script.

    The exporter itself has no FreeCAD dependency. Generated scripts import
    ``FreeCAD`` and ``Part`` only when executed inside FreeCAD.
    """

    def render_neck_back(
        self,
        surface: NeckBackSurface,
        document_name: str = "CNCguitarwizard",
        object_name: str = "NeckBack",
    ) -> str:
        """Return a FreeCAD script that lofts the neck-back solid.

        Args:
            surface: Backend-independent neck-back surface.
            document_name: FreeCAD document identifier.
            object_name: FreeCAD object identifier.

        Returns:
            Standalone Python source for execution inside FreeCAD.
        """
        rows = tuple(self._close_neck_row(row) for row in surface.mesh.rows)
        return self._render_loft_script(rows, document_name, object_name)

    def render_fretboard(
        self,
        surface: FretboardSurface,
        document_name: str = "CNCguitarwizard",
        object_name: str = "Fretboard",
    ) -> str:
        """Return a FreeCAD script that lofts the fretboard solid.

        Args:
            surface: Backend-independent fretboard playing surface.
            document_name: FreeCAD document identifier.
            object_name: FreeCAD object identifier.

        Returns:
            Standalone Python source for execution inside FreeCAD.
        """
        rows = tuple(self._close_fretboard_row(row) for row in surface.mesh.rows)
        return self._render_loft_script(rows, document_name, object_name)

    def write_script(self, path: Path, source: str) -> None:
        """Write generated FreeCAD source using UTF-8 encoding.

        Args:
            path: Destination ``.py`` or ``.FCMacro`` path.
            source: Script returned by a render method.
        """
        if path.suffix not in {".py", ".FCMacro"}:
            raise FreeCADBackendError(
                "FreeCAD scripts must use a .py or .FCMacro suffix."
            )
        path.write_text(source, encoding="utf-8")

    @staticmethod
    def _close_neck_row(row: tuple[Point3D, ...]) -> tuple[Point3D, ...]:
        """Close one neck-back section across the fretboard underside."""
        first = row[0]
        last = row[-1]
        return (*row, Point3D(last.x, last.y, 0.0), Point3D(first.x, first.y, 0.0))

    @staticmethod
    def _close_fretboard_row(row: tuple[Point3D, ...]) -> tuple[Point3D, ...]:
        """Close one radiused fretboard section across its flat underside."""
        first = row[0]
        last = row[-1]
        return (*row, Point3D(last.x, last.y, 0.0), Point3D(first.x, first.y, 0.0))

    def _render_loft_script(
        self,
        rows: tuple[tuple[Point3D, ...], ...],
        document_name: str,
        object_name: str,
    ) -> str:
        """Return common FreeCAD loft source for closed section rows."""
        self._validate_identifier(document_name, "document")
        self._validate_identifier(object_name, "object")
        serialized_rows = json.dumps(
            [
                [[point.x, point.y, point.z] for point in row]
                for row in rows
            ],
            separators=(",", ":"),
        )

        return (
            '"""Generated by CNCguitarwizard. Do not edit manually."""\n\n'
            "import FreeCAD as App\n"
            "import Part\n\n"
            f"SECTION_POINTS = {serialized_rows}\n\n"
            "def closed_wire(points):\n"
            '    """Create one closed polygon wire from XYZ triples."""\n'
            "    vectors = [App.Vector(x, y, z) for x, y, z in points]\n"
            "    vectors.append(vectors[0])\n"
            "    return Part.makePolygon(vectors)\n\n"
            f'document = App.newDocument("{document_name}")\n'
            "sections = [closed_wire(points) for points in SECTION_POINTS]\n"
            "shape = Part.makeLoft(sections, True, False, False)\n"
            f'feature = document.addObject("Part::Feature", "{object_name}")\n'
            "feature.Shape = shape\n"
            "document.recompute()\n"
        )

    @staticmethod
    def _validate_identifier(value: str, label: str) -> None:
        """Reject names that are unsafe in generated source and FreeCAD."""
        if not _VALID_IDENTIFIER.fullmatch(value):
            raise FreeCADBackendError(
                f"FreeCAD {label} name must be a valid identifier."
            )
