"""Generate deterministic Python scripts for execution inside FreeCAD."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from ...geometry.fretboard import FretboardSurface
from ...geometry.neck import NeckBackSurface
from ...geometry.primitives import Point3D
from .exceptions import FreeCADBackendError

_VALID_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True, slots=True)
class FreeCADScriptExporter:
    """Render loft-ready geometry as a standalone FreeCAD Python script.

    The exporter itself has no FreeCAD dependency. Generated scripts import
    ``FreeCAD`` and ``Part`` only when executed inside FreeCAD.
    """

    def render_neck_back(
        self,
        surface: NeckBackSurface,
        document_name: str = "CNCguitarwizard",
        object_name: str = "NeckBack",
        fcstd_path: Path | None = None,
        step_path: Path | None = None,
    ) -> str:
        """Return a FreeCAD script that lofts the neck-back solid.

        Args:
            surface: Backend-independent neck-back surface.
            document_name: FreeCAD document identifier.
            object_name: FreeCAD object identifier.
            fcstd_path: Optional destination for the FreeCAD document.
            step_path: Optional destination for the STEP model.

        Returns:
            Standalone Python source for execution inside FreeCAD.
        """
        rows = tuple(self._close_neck_row(row) for row in surface.mesh.rows)
        return self._render_loft_script(
            rows,
            document_name,
            object_name,
            fcstd_path,
            step_path,
        )

    def render_fretboard(
        self,
        surface: FretboardSurface,
        document_name: str = "CNCguitarwizard",
        object_name: str = "Fretboard",
        fcstd_path: Path | None = None,
        step_path: Path | None = None,
    ) -> str:
        """Return a FreeCAD script that lofts the fretboard solid.

        Args:
            surface: Backend-independent fretboard playing surface.
            document_name: FreeCAD document identifier.
            object_name: FreeCAD object identifier.
            fcstd_path: Optional destination for the FreeCAD document.
            step_path: Optional destination for the STEP model.

        Returns:
            Standalone Python source for execution inside FreeCAD.
        """
        rows = tuple(self._close_fretboard_row(row) for row in surface.mesh.rows)
        return self._render_loft_script(
            rows,
            document_name,
            object_name,
            fcstd_path,
            step_path,
        )

    def render_neck_assembly(
        self,
        neck_surface: NeckBackSurface,
        fretboard_surface: FretboardSurface,
        document_name: str = "CNCguitarwizard",
        neck_object_name: str = "NeckBack",
        fretboard_object_name: str = "Fretboard",
        fcstd_path: Path | None = None,
        step_path: Path | None = None,
    ) -> str:
        """Return a FreeCAD script containing neck and fretboard solids.

        The two solids remain separate document objects so their fit and
        manufacturing geometry can be inspected independently.

        Args:
            neck_surface: Backend-independent neck-back surface.
            fretboard_surface: Backend-independent fretboard surface.
            document_name: FreeCAD document identifier.
            neck_object_name: FreeCAD identifier for the neck object.
            fretboard_object_name: FreeCAD identifier for the fretboard.
            fcstd_path: Optional destination for the FreeCAD document.
            step_path: Optional destination for the combined STEP export.

        Returns:
            Standalone Python source for execution inside FreeCAD.
        """
        self._validate_identifier(document_name, "document")
        self._validate_identifier(neck_object_name, "neck object")
        self._validate_identifier(fretboard_object_name, "fretboard object")
        if neck_object_name == fretboard_object_name:
            raise FreeCADBackendError(
                "Neck and fretboard object names must be different."
            )
        self._validate_output_path(fcstd_path, {".fcstd"}, "FreeCAD")
        self._validate_output_path(step_path, {".step", ".stp"}, "STEP")

        neck_rows = tuple(
            self._close_neck_row(row) for row in neck_surface.mesh.rows
        )
        fretboard_rows = tuple(
            self._close_fretboard_row(row)
            for row in fretboard_surface.mesh.rows
        )
        output_commands = self._render_output_commands(
            fcstd_path,
            step_path,
            "[neck_feature, fretboard_feature]",
        )

        return (
            '"""Generated by CNCguitarwizard. Do not edit manually."""\n\n'
            "import FreeCAD as App\n"
            "import Part\n\n"
            f"NECK_SECTION_POINTS = {self._serialize_rows(neck_rows)}\n"
            "FRETBOARD_SECTION_POINTS = "
            f"{self._serialize_rows(fretboard_rows)}\n\n"
            "def make_loft(section_points):\n"
            '    """Create a solid loft from closed XYZ sections."""\n'
            "    sections = []\n"
            "    for points in section_points:\n"
            "        vectors = [App.Vector(x, y, z) for x, y, z in points]\n"
            "        vectors.append(vectors[0])\n"
            "        sections.append(Part.makePolygon(vectors))\n"
            "    return Part.makeLoft(sections, True, False, False)\n\n"
            f'document = App.newDocument("{document_name}")\n'
            "neck_feature = document.addObject("
            f'"Part::Feature", "{neck_object_name}")\n'
            "neck_feature.Shape = make_loft(NECK_SECTION_POINTS)\n"
            "fretboard_feature = document.addObject("
            f'"Part::Feature", "{fretboard_object_name}")\n'
            "fretboard_feature.Shape = make_loft("
            "FRETBOARD_SECTION_POINTS)\n"
            "document.recompute()\n"
            f"{output_commands}"
        )

    def write_script(self, path: Path, source: str) -> None:
        """Write generated FreeCAD source using UTF-8 encoding.

        Args:
            path: Destination ``.py`` or ``.FCMacro`` path.
            source: Script returned by a render method.
        """
        if path.suffix not in {".py", ".FCMacro"}:
            raise FreeCADBackendError(
                "FreeCAD scripts must use a .py or .FCMacro suffix."
            )
        path.write_text(source, encoding="utf-8")

    @staticmethod
    def _close_neck_row(row: tuple[Point3D, ...]) -> tuple[Point3D, ...]:
        """Close one neck-back section across the fretboard underside."""
        first = row[0]
        last = row[-1]
        return (*row, Point3D(last.x, last.y, 0.0), Point3D(first.x, first.y, 0.0))

    @staticmethod
    def _close_fretboard_row(row: tuple[Point3D, ...]) -> tuple[Point3D, ...]:
        """Close one radiused fretboard section across its flat underside."""
        first = row[0]
        last = row[-1]
        return (*row, Point3D(last.x, last.y, 0.0), Point3D(first.x, first.y, 0.0))

    def _render_loft_script(
        self,
        rows: tuple[tuple[Point3D, ...], ...],
        document_name: str,
        object_name: str,
        fcstd_path: Path | None,
        step_path: Path | None,
    ) -> str:
        """Return common FreeCAD loft source for closed section rows."""
        self._validate_identifier(document_name, "document")
        self._validate_identifier(object_name, "object")
        self._validate_output_path(fcstd_path, {".fcstd"}, "FreeCAD")
        self._validate_output_path(step_path, {".step", ".stp"}, "STEP")
        serialized_rows = self._serialize_rows(rows)
        output_commands = self._render_output_commands(
            fcstd_path,
            step_path,
            "[feature]",
        )

        return (
            '"""Generated by CNCguitarwizard. Do not edit manually."""\n\n'
            "import FreeCAD as App\n"
            "import Part\n\n"
            f"SECTION_POINTS = {serialized_rows}\n\n"
            "def closed_wire(points):\n"
            '    """Create one closed polygon wire from XYZ triples."""\n'
            "    vectors = [App.Vector(x, y, z) for x, y, z in points]\n"
            "    vectors.append(vectors[0])\n"
            "    return Part.makePolygon(vectors)\n\n"
            f'document = App.newDocument("{document_name}")\n'
            "sections = [closed_wire(points) for points in SECTION_POINTS]\n"
            "shape = Part.makeLoft(sections, True, False, False)\n"
            f'feature = document.addObject("Part::Feature", "{object_name}")\n'
            "feature.Shape = shape\n"
            "document.recompute()\n"
            f"{output_commands}"
        )

    @staticmethod
    def _render_output_commands(
        fcstd_path: Path | None,
        step_path: Path | None,
        step_objects: str,
    ) -> str:
        """Return optional FreeCAD document and STEP export commands."""
        commands: list[str] = []
        if fcstd_path is not None:
            path_literal = json.dumps(str(fcstd_path))
            commands.append(f"document.saveAs({path_literal})")
        if step_path is not None:
            path_literal = json.dumps(str(step_path))
            commands.append(f"Part.export({step_objects}, {path_literal})")
        if not commands:
            return ""
        return "\n".join(commands) + "\n"

    @staticmethod
    def _serialize_rows(rows: tuple[tuple[Point3D, ...], ...]) -> str:
        """Return compact deterministic JSON for section coordinates."""
        return json.dumps(
            [
                [[point.x, point.y, point.z] for point in row]
                for row in rows
            ],
            separators=(",", ":"),
        )

    @staticmethod
    def _validate_identifier(value: str, label: str) -> None:
        """Reject names that are unsafe in generated source and FreeCAD."""
        if not _VALID_IDENTIFIER.fullmatch(value):
            raise FreeCADBackendError(
                f"FreeCAD {label} name must be a valid identifier."
            )

    @staticmethod
    def _validate_output_path(
        path: Path | None,
        allowed_suffixes: set[str],
        label: str,
    ) -> None:
        """Reject output paths with a format-specific invalid suffix."""
        if path is not None and path.suffix.lower() not in allowed_suffixes:
            suffixes = " or ".join(sorted(allowed_suffixes))
            raise FreeCADBackendError(
                f"{label} output path must use a {suffixes} suffix."
            )
