"""Turn a single-stroke SVG font into a Python module for geometry.fonts.

The engraving fonts come from Inkscape's Hershey Text extension
(``share/inkscape/extensions/svg_fonts``), single-stroke SVG fonts by Evil
Mad Scientist. Each glyph's path (M, L, C, Z, absolute) is turned into
polylines in font units (Y up, baseline at 0), its curves sampled
``CURVE_SAMPLES`` to a segment, and written out as plain tuples, so the
package needs no font library (it also runs in the browser). Only the
characters in ``CHARACTERS`` are kept.

Usage::

    python tools/import_svg_font.py HersheyScriptMed.svg script \\
        src/cncguitarwizard/geometry/fonts/script.py
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

CHARACTERS = "".join(chr(code) for code in range(32, 127)) + "äöåÄÖÅüÜéÉ"
"""Printable ASCII and the Nordic letters a name may need."""

CURVE_SAMPLES = 8
"""Points a cubic curve is sampled to."""

HERSHEY_NOTICE = """The Hershey Fonts were originally created by Dr. A. V. Hershey while
working at the U. S. National Bureau of Standards. The format of the Font
data in this distribution was originally created by James Hurt,
Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821
(mit-eddie!ci-dandelion!hurt). This SVG conversion was prepared by
Windell H. Oskay, www.evilmadscientist.com (from emergent.unpythonic.net/
software/hershey by way of "Hershey Fonts in SVG" by Marty McGuire)."""


def strokes(path: str) -> list[list[tuple[float, float]]]:
    """Return the polylines one glyph's path draws."""
    tokens = re.findall(r"[MLCZ]|-?\d*\.?\d+(?:e-?\d+)?", path, re.IGNORECASE)
    lines: list[list[tuple[float, float]]] = []
    current: list[tuple[float, float]] = []
    command = ""
    index = 0

    def number() -> float:
        nonlocal index
        index += 1
        return float(tokens[index - 1])

    while index < len(tokens):
        token = tokens[index]
        if token in "MLCZ":
            command = token
            index += 1
            if token == "Z" and current:
                current.append(current[0])
            continue
        if command == "M":
            if len(current) > 1:
                lines.append(current)
            current = [(number(), number())]
            command = "L"
        elif command == "L":
            current.append((number(), number()))
        elif command == "C":
            p0 = current[-1]
            c1 = (number(), number())
            c2 = (number(), number())
            p3 = (number(), number())
            for k in range(1, CURVE_SAMPLES + 1):
                t = k / CURVE_SAMPLES
                u = 1.0 - t
                current.append(
                    (
                        u**3 * p0[0]
                        + 3 * u * u * t * c1[0]
                        + 3 * u * t * t * c2[0]
                        + t**3 * p3[0],
                        u**3 * p0[1]
                        + 3 * u * u * t * c1[1]
                        + 3 * u * t * t * c2[1]
                        + t**3 * p3[1],
                    )
                )
        else:
            raise ValueError(f"Unsupported path command {command!r} in {path!r}")
    if len(current) > 1:
        lines.append(current)
    return lines


def main(source: str, name: str, target: str) -> None:
    text = Path(source).read_text(encoding="utf-8")
    title = re.search(r"Font name:\s*(.+)", text)
    default = re.search(r"<font\b[^>]*horiz-adv-x=\"([\d.]+)\"", text)
    glyphs: dict[str, tuple[float, list[list[tuple[float, float]]]]] = {}
    for match in re.finditer(r"<glyph\b([^>]*?)/?>", text, re.S):
        attributes = match.group(1)
        found = re.search(r'unicode="([^"]*)"', attributes)
        if not found:
            continue
        character = html.unescape(found.group(1))
        if character not in CHARACTERS:
            continue
        advance = re.search(r'horiz-adv-x="([-\d.]+)"', attributes)
        path = re.search(r'\sd="([^"]*)"', attributes)
        glyphs[character] = (
            float(advance.group(1)) if advance else float(default.group(1)),
            strokes(path.group(1)) if path else [],
        )
    cap_height = max(y for line in glyphs["H"][1] for _, y in line)
    lines = [
        f'"""{title.group(1).strip() if title else name}: a single-stroke font.',
        "",
        f"Generated by tools/import_svg_font.py from {Path(source).name}; font units,",
        "Y up, baseline at 0. Do not edit by hand.",
        "",
        HERSHEY_NOTICE,
        '"""',
        "",
        f"CAP_HEIGHT = {round(cap_height)}",
        '"""Height of the capital H, in font units."""',
        "",
        "GLYPHS: dict[str, tuple[int, tuple[tuple[tuple[int, int], ...], ...]]] = {",
    ]
    for character in CHARACTERS:
        if character not in glyphs:
            continue
        advance, polylines = glyphs[character]
        drawn = tuple(
            tuple((round(x), round(y)) for x, y in line) for line in polylines
        )
        lines.append(f"    {character!r}: ({round(advance)}, {drawn!r}),")
    lines += ["}", '"""Each glyph\'s advance and strokes, in font units."""', ""]
    Path(target).write_text("\n".join(lines), encoding="utf-8")
    print(f"{target}: {len(glyphs)} glyphs, cap height {cap_height:g}")


if __name__ == "__main__":
    main(*sys.argv[1:4])
